name: Build and Push Multiple Docker Images

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Choose which job to run'
        required: true
        default: 'build-base'
        type: choice
        options:
          - build-riscv
          - build-rust
          - build-cpp
          - build-base

jobs:
  build-base:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'build-base' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        id: docker-cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker base image 
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/base:latest
          push: true
          
  build-rust:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'build-rust' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Cache Docker layers
        id: docker-cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker rust image 
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-Rust
          tags: ghcr.io/${{ github.repository_owner }}/rust:latest
          push: true

  build-cpp:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'build-cpp' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Cache Docker layers
        id: docker-cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker Cpp image 
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-Cpp
          tags: ghcr.io/${{ github.repository_owner }}/cpp:latest
          push: true

  build-riscv:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'build-riscv' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        id: docker-cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker Risc-V image 
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-Riscv
          tags: ghcr.io/${{ github.repository_owner }}/riscv:latest
          push: true


